// BORRADOR DE COPY — Mario escribe la versión final de todos los textos.
export const es = {
  appName: "Plataforma de clases",
  common: {
    loading: "Cargando…",
  },
  login: {
    title: "Bienvenido",
    subtitle: "Inicia sesión con tu cuenta de Google",
    error: "No se pudo iniciar sesión. Intenta de nuevo.",
  },
  onboarding: {
    title: "Crea tu perfil",
    usernameLabel: "Username",
    usernameHint: "3-20 caracteres: letras minúsculas, números y _",
    usernameTaken: "Ese username ya está ocupado",
    bioLabel: "Bio",
    bioPlaceholder: "Cuéntanos quién eres…",
    submit: "Continuar",
    genericError: "Ocurrió un error. Intenta de nuevo.",
  },
  home: {
    feedComingSoon: "El feed llega en la Fase 1 🚧",
  },
  nav: {
    menu: "Menú",
    home: "Inicio",
    profile: "Perfil",
    classes: "Mis clases",
    settings: "Configuración",
    create: "Crear",
    logout: "Cerrar sesión",
  },
  classes: {
    title: "Mis clases",
    teaching: "Clases que doy",
    enrolled: "Clases donde estoy",
    empty: "Aún no estás en ninguna clase.",
    create: "Crear clase",
    join: "Unirme con código",
    codeLabel: "Código de la clase",
    joinSubmit: "Unirme",
    name: "Nombre de la clase",
    prefix: "Prefijo del código (ej. MICRO)",
    startDate: "Fecha de inicio",
    endDate: "Fecha de fin",
    schedule: "Horario",
    addBlock: "Agregar horario",
    createSubmit: "Crear",
    copyLink: "Copiar link de invitación",
    linkCopied: "¡Link copiado!",
    days: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
  },
  feed: {
    empty: "Nada por aquí todavía. ¡Sé el primero en publicar!",
    end: "Llegaste al final",
    error: "No se pudo cargar el feed. Desliza para reintentar.",
    deletedPost: "[eliminado]",
    participacionBadge: "Participación",
    tareaBadge: "Tarea",
    entregaBadge: "Entrega",
    dueOn: "Entrega {date}",
    replies: "respuestas",
    like: "Me gusta",
    unlike: "Quitar me gusta",
  },
  post: {
    replyPlaceholder: "Responde algo…",
    replySubmit: "Responder",
    deleteConfirmTitle: "¿Eliminar publicación?",
    deleteConfirmBody: "Se eliminará y sus puntos serán revocados.",
    deleteConfirm: "Eliminar",
    cancel: "Cancelar",
    likeError: "No se pudo registrar el like",
    deleteError: "No se pudo eliminar",
    replyError: "No se pudo publicar la respuesta",
    attachmentError: "No se pudo abrir el archivo",
    entregaToggle: "Es mi entrega",
    entregaOnTime: "Entrega a tiempo · 100%",
    entregaUnder24h: "Con retraso · 90%",
    entregaUnderWeek: "Con retraso · 50%",
    entregaLate: "Muy atrasada · 20%",
    entregaReplaces: "Reemplaza tu entrega anterior",
    scoreBadge: "Calificación {n}",
    feedbackFrom: "Comentario del profesor",
    vetoedNotice: "Esta participación no cuenta",
    examenBadge: "Examen",
  },
  revisar: {
    title: "Revisar",
    tabEntregas: "Entregas",
    tabExamenes: "Exámenes",
    tabParticipaciones: "Participaciones",
    pending: "{n} sin abrir",
    empty: "Nada por revisar",
    autoScore: "Automático {n}",
    saveAndNext: "Guardar y siguiente",
    save: "Guardar",
    feedbackLabel: "Comentario para el alumno",
    scoreLabel: "Calificación",
    scoreInvalid: "La calificación debe estar entre {low} y {high}",
    markGraded: "Marcar como calificado",
    unmarkGraded: "Quitar calificado",
    markGradedWarning: "{n} alumnos sin calificación contarán como 0.",
    graded: "Calificado",
    veto: "Vetar",
    unveto: "Quitar veto",
    vetoReasonLabel: "Motivo (opcional)",
    vetoed: "Vetada",
    saveError: "No se pudo guardar",
  },
  compose: {
    title: "Nueva publicación",
    modeRegular: "Publicación",
    modeParticipacion: "Participación",
    modeTarea: "Tarea",
    modeExamen: "Examen",
    examenModeLabel: "Modalidad",
    examenPaper: "En papel",
    examenDigital: "Entrega digital",
    examenPlaceholder: "¿Qué examen es y qué cubre?",
    placeholder: "¿Qué está pasando en clase?",
    participacionPlaceholder:
      "Explica tu participación con detalle para que cuente…",
    tareaPlaceholder: "¿Qué deben hacer y para cuándo?",
    participacionHint: "Escribe tu explicación y luego da tap: 1, 2 o 3 veces",
    tapToRegister: "Tap para registrar",
    double: "¡Doble!",
    triple: "¡Triple!",
    publishing: "Publicando…",
    published: "¡Registrada! +{n} pts",
    publish: "Publicar",
    attach: "Adjuntar",
    classLabel: "Clase",
    dueLabel: "Entrega",
    dueHint: "Por defecto: el próximo domingo",
    tooShort: "Explica con más detalle (mínimo 10 caracteres)",
    error: "No se pudo publicar. Intenta de nuevo.",
    cancelTap: "Cancelar",
  },
  grade: {
    points: "pts",
    title: "Tu calificación",
    tareas: "Tareas",
    examenes: "Exámenes",
    notEvaluated: "—",
    noTareasYet: "sin tareas asignadas aún",
    noExamenesYet: "sin exámenes aún",
    participaciones: "Participaciones",
    likes: "Likes recibidos",
    likesWithCount: "{n} likes",
    faltas: "Faltas",
    empty: "Aún no tienes puntos. ¡Participa en clase o publica en el foro!",
    error: "No se pudo cargar tu calificación",
    close: "Cerrar",
  },
  configurar: {
    title: "Configurar",
    sectionWeights: "Pesos y puntos",
    tareasWeightLabel: "Peso tareas",
    examenesWeightLabel: "Peso exámenes",
    tapValueLabel: "Puntos por tap",
    likeValueLabel: "Puntos base por like",
    likeExponentLabel: "Exponente de likes",
    saveSettings: "Guardar",
    settingsSaved: "Configuración guardada",
    settingsError: "No se pudo guardar la configuración",
    sectionIncentivos: "Puntos extra (incentivos)",
    incentiveNameLabel: "Nombre",
    incentivePointsLabel: "Puntos",
    addIncentive: "Agregar",
    deleteIncentive: "Eliminar",
    deleteConfirm: "¿Eliminar este incentivo?",
    deleteConfirmBody: "Si ya fue otorgado, quedará oculto pero sus puntos se conservarán.",
    deleteConfirmYes: "Eliminar",
    cancel: "Cancelar",
    otorgar: "Otorgar",
    otorgarTitle: "Otorgar puntos",
    pickStudent: "Selecciona un alumno",
    otorgarConfirm: "Otorgar",
    otorgarSuccess: "Puntos otorgados",
    otorgarError: "No se pudo otorgar",
    createError: "No se pudo crear el incentivo",
    noIncentives: "Aún no hay incentivos. Agrega el primero arriba.",
    empty: "Sin clases asignadas.",
  },
} as const;
