"""tarea columns on posts

Revision ID: 1e3a1a53039d
Revises: 35864b6a75e3
Create Date: 2026-07-30 10:44:29.869168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3a1a53039d'
down_revision: Union[str, Sequence[str], None] = '35864b6a75e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('is_entrega', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_entrega')
    op.drop_column('posts', 'due_date')
    # ### end Alembic commands ###
