"""points_config and reviews

Revision ID: b67f3cfb2574
Revises: 1e3a1a53039d
Create Date: 2026-07-30 14:11:49.359021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67f3cfb2574'
down_revision: Union[str, Sequence[str], None] = '1e3a1a53039d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('tap_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('like_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('like_exponent', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('like_cap', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('daily_post_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_config_class_id'), 'points_config', ['class_id'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_post_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('auto_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entrega_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_entrega_post_id'), 'reviews', ['entrega_post_id'], unique=True)
    # ### end Alembic commands ###

    op.execute(
        "INSERT INTO points_config (class_id, tap_value, like_value, "
        "like_exponent, daily_post_limit) "
        "SELECT id, 1.0, 1.0, 0.5, 5 FROM classes"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_entrega_post_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_points_config_class_id'), table_name='points_config')
    op.drop_table('points_config')
    # ### end Alembic commands ###
