"""participacion reviewed

Revision ID: c02ad66222b5
Revises: 22f0157e4d8c
Create Date: 2026-08-03 11:12:48.265546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02ad66222b5'
down_revision: Union[str, Sequence[str], None] = '22f0157e4d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    # Named explicitly: autogenerate emits None, and PostgreSQL — which is what
    # CI and prod run — cannot drop an unnamed constraint. SQLite cannot ALTER a
    # table to add a foreign key at all, so it is skipped there; local dev keeps
    # working because SQLite does not enforce FKs anyway.
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_posts_reviewed_by_users", "posts", "users", ["reviewed_by"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_posts_reviewed_by_users", "posts", type_="foreignkey")
    op.drop_column('posts', 'reviewed_by')
    op.drop_column('posts', 'reviewed_at')
    # ### end Alembic commands ###
